/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/mobileui.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./public/models/mobileui.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['000_header'].geometry} material={materials['Material.004']} position={[2.13, 1.257, 2.231]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['001_Screen'].geometry} material={materials['Belize_0ee18ca0-b09e-4a0d-be31-9fd2d86a859a']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['002_Flash'].geometry} material={materials['Flash 1_668c1d23-a602-465d-892b-fb34e93651c6']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['003_Back_Panel'].geometry} material={materials['Rear Glass 1_7fdfec86-b5e4-493c-a357-c9640777bde3']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['004_Main_Body'].geometry} material={materials['Body 1_b1f4a169-0812-41a8-9cd6-7cb04d36d549']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['005_Ports'].geometry} material={materials['Ports 1_cc9a512f-511e-4f50-9bef-77f54c40f318']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['006_Side_Button'].geometry} material={materials['Power Button 1_8df2732c-a7c4-4aee-a39d-ab786f8e97f4']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['007_Front_Frame'].geometry} material={materials['Front Glass 1_8b99746d-7a5e-47ed-9a2c-4c99448826fc']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['008_Camera_Rim'].geometry} material={materials['Camera Rim 1_6792e99d-824e-4004-a1cf-6e41d5ef1d10']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['009_Camera_Body'].geometry} material={materials['Camera Body 1_468a4040-f9e9-45a6-895b-035fceb79516']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['010_Cameras'].geometry} material={materials['Camera Lenses 1_f3fea960-fe21-42b0-88da-749564c4aeb5']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['011_Camers_Lenses'].geometry} material={materials['Camera Glass 1_b36d1b91-8c7b-416a-8b18-33b994007f9b']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
      <mesh geometry={nodes['012_Camera_Lenses_Out'].geometry} material={materials['Camera Rims 1_f016c3b0-feb8-4caa-b773-c3a510bfd5b9']} position={[0.069, -0.315, 1.965]} rotation={[Math.PI / 2, 0, 0]} scale={0.137} />
    </group>
  )
}

useGLTF.preload('./public/models/mobileui.glb')
